"""SSOT — resolution + every resolution-derived size and bit-width (the §1 2-const switch).

W/H live ONLY here; everything resolution-derived (table sizes, pow2 pads, AND bit-widths) is
computed from them — no literal that assumes W/H <= 256 (DESIGN §1, §1.1.4). `emit_fj_consts`
writes build/generated/fj_consts.fj, the constants file src/fj/memory_map.fj consumes, so the
fj side and the host side cannot drift (R6). The host span ledger here is the skeleton M10 (R0)
fills with real per-table numbers (§1.2).
"""
from __future__ import annotations
import math
from dataclasses import dataclass
from pathlib import Path

# Default flat-limit (span-words) — flipjump's 2**23 (64 MB at w=32), §1.2. The R-3 budget ceiling.
FLAT_MAX_WORDS = 1 << 23


@dataclass(frozen=True)
class Config:
    # ── the two resolution constants (the §1 2-const switch) ──
    W: int = 160
    H: int = 100
    # ── other base constants ──
    BPP: int = 8        # bits/pixel -> 256 colors
    TRIG_N: int = 4096  # trig LUT entries, 16**3 (§1.2/§2.1)
    NATIVE_W: int = 320  # DOOM's native authoring width (the F8 UI + D5 texture downscale reference)

    @property
    def TEXTURE_DOWNSCALE(self) -> int:
        """World-texture D5 span-lever factor = NATIVE_W // W: 2 at W=160 (the R0 decision), 1 at the
        native 320 (no downscale — raise --flat-max-words instead, DESIGN §1.2 320 stretch). The single
        bit-exact factor shared by the texture compiler (H4) and the oracle (H5) — R6/D12."""
        return max(1, self.NATIVE_W // self.W)

    # ── resolution-derived (computed; NEVER hardcoded) ──
    @property
    def NCOLORS(self) -> int:
        return 1 << self.BPP

    @property
    def COL_BITS(self) -> int:
        """Screen column-x width = ceil(log2 W), §1.1.4 — 8 at W=160, 9 at W=320; never a fixed 8."""
        return math.ceil(math.log2(self.W))

    @property
    def ROW_BITS(self) -> int:
        """Screen row-y width = ceil(log2 H)."""
        return math.ceil(math.log2(self.H))

    @property
    def VIEW_W(self) -> int:
        """3D viewport width (full screen until a status bar exists, R3 — §10.4 VIEW_H note)."""
        return self.W

    @property
    def VIEW_H(self) -> int:
        return self.H

    @property
    def CENTERX(self) -> int:
        """Screen-centre column = VIEW_W//2 (the projection's horizontal vanishing point, M12)."""
        return self.VIEW_W // 2

    @property
    def CENTERY(self) -> int:
        """Screen-centre row = VIEW_H//2 (the horizon: wall top/bottom = CENTERY -/+ height*scale, M12)."""
        return self.VIEW_H // 2

    @property
    def PROJECTION(self) -> int:
        """Focal length in column units. FOV = 90deg => focal = CENTERX (tan 45deg = 1), so the screen
        edges sit at +/-45deg (D6 projection setup; viewangletox is built from this)."""
        return self.CENTERX

    @property
    def FB_SIZE(self) -> int:
        """Framebuffer: W*H packed bytes, no align (§1.2)."""
        return self.W * self.H

    @property
    def PALETTE_SIZE(self) -> int:
        """NCOLORS * 3 (RGB triplets), §1.2."""
        return self.NCOLORS * 3

    def constants(self) -> dict:
        """The full set of fj-visible constants (the SSOT contents emitted to fj_consts.fj)."""
        return {
            "W": self.W, "H": self.H, "BPP": self.BPP, "TRIG_N": self.TRIG_N,
            "NCOLORS": self.NCOLORS, "COL_BITS": self.COL_BITS, "ROW_BITS": self.ROW_BITS,
            "VIEW_W": self.VIEW_W, "VIEW_H": self.VIEW_H,
            "CENTERX": self.CENTERX, "CENTERY": self.CENTERY, "PROJECTION": self.PROJECTION,
            "FB_SIZE": self.FB_SIZE, "PALETTE_SIZE": self.PALETTE_SIZE,
        }

    def span_ledger(self) -> dict:
        """Skeleton §1.2 address-span ledger (the M1 home). M10 (R0) fills the real per-table numbers."""
        return {"framebuffer": self.FB_SIZE, "palette": self.PALETTE_SIZE}

    def total_span(self) -> int:
        return sum(self.span_ledger().values())

    def emit_fj_consts(self, out="build/generated/fj_consts.fj") -> Path:
        """Write the SSOT constants as FlipJump `NAME = value` definitions for memory_map.fj."""
        # ASCII-only + explicit utf-8: flipjump's parser reads files as utf-8, and Path.write_text
        # would otherwise use the Windows locale codec (cp1252) and emit a non-utf-8 byte.
        lines = [
            "// GENERATED by doomfj.config -- DO NOT EDIT. Single source of truth: src/doomfj/config.py",
            f"// resolution {self.W}x{self.H}, bpp={self.BPP} ({self.NCOLORS} colors)",
            "",
        ]
        lines += [f"{name} = {val}" for name, val in self.constants().items()]
        out = Path(out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return out
